# example netlify.toml
[build]
  command = "cd website && pnpm install && pnpm run build"
  functions = "netlify/functions"
  publish = "website/dist"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF website/ popurris/ docs/"

[[redirects]]
  from = "https://divino.planisferio.cl/*"
  to = "https://divinoanticristo.cl/:splat"
  status = 301
  force = true

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
